// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loidoxjkkquhqejghngr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvaWRveGpra3F1aHFlamdobmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Nzc4ODIsImV4cCI6MjA1NjE1Mzg4Mn0.4rwT25GnjryrzEzfKTy0-cV_O_IlfrOZgeYAac63BsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);